### ISSUE TITLE
Support Android NDK r14b, for Unreal Engine

### ISSUE THREAD

**Issue by Superxwolf** [heroiclabs/nakama-cpp#11]
Currently as of the latest version, Unreal Engine 4.21 uses Android NDK r14b for Android, it is an old NDK which is not support with Nakama.

I know we've talked about this, just wanted to know if there's any updates on release time.

**Comment by mofirouz** [comment]
We are tackling the Unreal client update at the moment. This is in a separate GitHub repo. This is a valid issue, please re-open it here so discussion can be more relevant:

https://github.com/heroiclabs/nakama-unreal

**Comment by Superxwolf** [comment]
Alright, following discussion [there](https://github.com/heroiclabs/nakama-unreal/issues/14#issuecomment-475600403).
