### ISSUE TITLE
Issue building for Unreal 5

### ISSUE THREAD

**Issue by AdLegg85** [heroiclabs/nakama-cpp#146]
I have been trying to get Nakama working with unreal 5 - following [this video ](https://www.youtube.com/watch?app=desktop&v=GmYZnc1HUZw) After adding Nakama into the plugins folder and selecting the plugin active. It will restart and try to compile but will fail with errors.

  NakamaCore.build.cs(26, 45): [CS0103] The name 'UnrealArch' does not exist in the current context
  NakamaCore.build.cs(22, 40): [CS0103] The name 'UnrealArch' does not exist in the current context

I followed the steps exactly, project is C++ and im running unreal 5.1.1

Thanks

**Comment by lugehorsam** [comment]
Hi @AdLegg85 this will be fixed in a release next week.

**Comment by lugehorsam** [comment]
This is now fixed in the latest `nakama-unreal` release.
