### ISSUE TITLE
Linux build fails

### ISSUE THREAD

**Issue by ascherbakhov** [heroiclabs/nakama-cpp#20]
Hi there!
I have a following backtrace with SIGSEGV on creating defaultClient(release 2.10 build)

`std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) 0x00007fa5303b719f
Nakama::RestClient::RestClient(Nakama::NClientParameters const&, std::shared_ptr<Nakama::NHttpTransportInterface>) 0x00007fa5327116d7
Nakama::createRestClient(Nakama::NClientParameters const&, std::shared_ptr<Nakama::NHttpTransportInterface>) 0x00007fa5326dc079
NCocosHelper::createDefaultClient NCocosHelper.cpp:32
HelloWorld::InitNetwork HelloWorldScene.cpp:141
HelloWorld::init HelloWorldScene.cpp:49
HelloWorld::create HelloWorldScene.h:41
HelloWorld::createScene HelloWorldScene.cpp:34
AppDelegate::applicationDidFinishLaunching AppDelegate.cpp:121
cocos2d::Application::run CCApplication-linux.cpp:70
main main.cpp:38
__libc_start_main 0x00007fa52f95cb97
_start 0x0000556e2dc5640a`

I haven't built yet nakama-cpp with debug symbols. Maybe you have any ideas before I have to check it

**Comment by Dimon4eg** [comment]
Hi, it crashes because you use Nakama library with another compiler version.
Please build nakama-cpp for Linux with your compiler.

**Comment by ascherbakhov** [comment]
I've done it, and it actually works, thank you!
By the way, what about gRPC client for cocos2d-x? I'm a little bit confused with "gRPC client is off."  in Nakama-cocos2d-x release page/

**Comment by mofirouz** [comment]
@ascherbakhov We've not turned on compilation of the client library with gRPC C++ Client library - as this uses HTTP/2 and is currently problematic. Instead, we are using the standard RESTful API that Nakama exposes which uses HTTP/1.1 just like every client library we have.

**Comment by ascherbakhov** [comment]
Thank you!
What about compiling in cpprest mode?
I failed to compile it: compiler didn't find cppprest headers, though rest client compiles successfully.

**Comment by Dimon4eg** [comment]
@ascherbakhov please post your config and error log.
for cocos2d you don't need cpprest.

**Comment by Dimon4eg** [comment]
I think fixed the error in https://github.com/heroiclabs/nakama-cpp/commit/0ab96965a6e71a0d13ea2265a64de37ae1187b77
Please pull latest changes and try again.

**Comment by ascherbakhov** [comment]
Yes, now it works, thank you.
