### ISSUE TITLE
UE4.24 compile error

### ISSUE THREAD

**Issue by irajsb** [heroiclabs/nakama-cpp#27]
`For external libraries use the full path in PublicAdditionalLibraries, if its a system library then use PublicSystemLibraries/PublicSystemLibraryPaths`

fix:
Replace PublicLibraryPaths with PublicAdditionalLibraries in build.cs
thanks.

**Comment by novabyte** [comment]
@irajsb Why did you close this issue? Was your problem solved?

**Comment by irajsb** [comment]
because i opened issue in wrong repo i had to open it in unreal repo
instead of cpp. problem  solved but that message still shows up as a
warning but works perfectly thanks!
