### ISSUE TITLE
Nakama::opt::optional performs unexpected conversions when compiling with different C++ language standards

### ISSUE THREAD

**Issue by Daspien27** [heroiclabs/nakama-cpp#31]
With further investigation, I can confirm it is due to misaligned language standards. By changing my project from C++latest to C++14 `Nakama::opt::make_optional` aligns with the `nonstd::optional_lite::optional` class.

This is unfortunate that the `nakama-cpp` headers changes types depending on the language version. I think a potential fix would be to provide the two optional class interfaces  in parallel (introducing a `std::optional` when available) or to just commit to a more hardened `Nakama::NOptional` type that could potentially allow conversions with `nonstd::optional_lite::optional` or `std::optional`.

_Originally posted by @Daspien27 in https://github.com/heroiclabs/nakama-cpp/issues/24#issuecomment-633558997_

**Comment by Dimon4eg** [comment]
Thanks for report of the error.
We will try to resolve it.
By now I propose two solutions:
1. build `nakama-cpp` with same C++ standard.
Open nakama-cpp\src\CMakeLists.txt, line 63 and set C++20:
```
target_compile_features(nakama-cpp PUBLIC cxx_std_20)
```
2. use  `nakama-cpp` as shared library
https://github.com/heroiclabs/nakama-cpp#use-as-dynamic-library

**Comment by Daspien27** [comment]
> Thanks for report of the error.
> We will try to resolve it.
> By now I propose two solutions:
> 
> 1. build `nakama-cpp` with same C++ standard.
>    Open nakama-cpp\src\CMakeLists.txt, line 63 and set C++20:
> 
> ```
> target_compile_features(nakama-cpp PUBLIC cxx_std_20)
> ```
> 
> 1. use  `nakama-cpp` as shared library
>    https://github.com/heroiclabs/nakama-cpp#use-as-dynamic-library

Opting to modify CMakeLists is more in line with my goals, and I can verify the incorrect behavior resolves.

Thanks for looking into resolving this error!

**Comment by Dimon4eg** [comment]
Great!
I think we will release static libs for C++17 and C++20 standard.
