### ISSUE TITLE
Call RPC without a session

### ISSUE THREAD

**Issue by Superxwolf** [heroiclabs/nakama-cpp#32]
Hello,

I would like to have the ability to call RPC from client without the need to authenticate first.

**Comment by Dimon4eg** [comment]
It's not supported by C++ client yet.
We will ad support soon.

**Comment by Dimon4eg** [comment]
I've implemented new `rpc` method with `http key` instead of session.
@Superxwolf can you build by self and try it?

**Comment by Superxwolf** [comment]
I actually want it for nakama-unreal, but since it's required at the cpp level, I opened an issue here first.

**Comment by Dimon4eg** [comment]
closing as issue has been fixed. nakama-unreal will be released separately soon.
