### ISSUE TITLE
Custom query matchMaker

### ISSUE THREAD

**Issue by raz0r007** [heroiclabs/nakama-cpp#33]
There's a problem when I try to find opponents using a custom query. When I use `query = "*"` it works. But if I try to use a custom query, for example `query = "+test:test"` it doesn't work anymore. Could we check it?

Topic in forums: https://forum.heroiclabs.com/t/custom-query-matchmaker/917

**Comment by lugehorsam** [comment]
@raz0r007 In your query string, you'll need to access the `test` via `properties`. 

Your query should look like: `query = "+properties.test:test"`

You can take a look at the code snippets from the (docs)[https://heroiclabs.com/docs/gameplay-matchmaker/].

**Comment by raz0r007** [comment]
I already tested `query = "+properties.test:test"` and it doesn't work either. Could we confirm if this feature is working on Nakama C++ API ? Is it working on your environment @lugehorsam  ?

Thanks

**Comment by raz0r007** [comment]
Thanks ! I fixed it.

**Comment by lugehorsam** [comment]
@raz0r007 awesome.
