### ISSUE TITLE
2.5.0 release does not have libs for iOS/OSX/Android

### ISSUE THREAD

**Issue by mrpuzzler** [heroiclabs/nakama-cpp#43]
Can't find precompile libs for iOS/OSX/Android. Could you please fix it?

**Comment by Dimon4eg** [comment]
https://github.com/heroiclabs/nakama-cpp/releases/tag/v2.5.1 has libs for Mac & Android.
iOS build is broken.

**Comment by mrpuzzler** [comment]
Do you plan to fix iOS builds?

**Comment by novabyte** [comment]
@mrpuzzler Yes, we're working on the iOS build support at the moment but in the meantime pull requests are always welcome. :pray:

**Comment by novabyte** [comment]
@mrpuzzler Yes, we're working on the iOS build support at the moment but in the meantime pull requests are always welcome. :pray:

**Comment by mrpuzzler** [comment]
It’s impossible to use library without all platforms.

Вт, 1 февр. 2022 г. в 18:29, Chris Molozian ***@***.***>:

**Comment by mofirouz** [comment]
Thanks @mrpuzzler, we are well aware of the issues and as @novabyte mentioned we are in the middle of fixing these. If you'd like these to be fixed sooner than we can, we'll gladly take all contributions from yourself and the community :+1:

**Comment by lugehorsam** [comment]
Hey @mrpuzzler we've reworked the build system and you should see the latest releases for the libraries you need.
