### ISSUE TITLE
Add more client and realtime tests

### ISSUE THREAD

**Issue by mofirouz** [heroiclabs/nakama-cpp#5]
- [x] Add tests for matchmaking.
- [x] Add tests for server-authoritative multiplayer. 
  - You'll need to use the existing [Lua modules](https://github.com/heroiclabs/nakama/blob/master/data/modules/clientrpc.lua#L68) to send a RPC request to create matches. 
- [x] Add test for creating and submitting tournaments.
  - You'll need to use this [Lua module](https://github.com/heroiclabs/nakama/blob/master/data/modules/tournament.lua#L71) to create tournaments.

**Comment by Dimon4eg** [comment]
Done.
