### ISSUE TITLE
nakama-cpp-wrapper doesn't copy partyId from C struct to NPartyPresenceEvent

### ISSUE THREAD

**Issue by mhaider-bitwisealchemy** [heroiclabs/nakama-cpp#51]
NPartyPresenceEvent partyId is always empty in my testing. I think the problem is in the assign function. I only see joins and leaves assigned.

**Comment by lugehorsam** [comment]
@mhaider-bitwisealchemy thanks for filing this issue -- we've resolved it by removing the intermediate wrapper layer entirely from the repository.
