### ISSUE TITLE
XCODE gives "Linker Command Failed with Exit Code 1" on 2.5.1 and 2.4.0

### ISSUE THREAD

**Issue by jkaplan55** [heroiclabs/nakama-cpp#53]
This may be something I'm doing wrong, but I've followed the instructions in the [readme](https://github.com/heroiclabs/nakama-cpp#setup-for-mac-and-ios-projects) to the best of my knowledge and I am unable to make it work.

I am aware there was an issue with 2.5.0, but I cannot build with 2.5.1 or 2.4.0 either.

The instructions say:
1. Add NAKAMA_CPP_SDK/include in Build Settings > Header Search Paths
2.  Add libs folder in Build Settings > Library Search Paths:
NAKAMA_CPP_SDK/libs/mac - for Mac

![image](https://user-images.githubusercontent.com/93295860/155259667-983dc75e-b20a-412a-b18f-c883ce525cc8.png)

3. In General > Frameworks, Libraries, and Embedded Content add following:
all .a files located in libs folder
foundation and security frameworks

![image](https://user-images.githubusercontent.com/93295860/155259818-029aa0a3-f999-46f5-934c-a3fbcaaf4230.png)

I get "Linker Command Failed with Exit Code 1"
![image](https://user-images.githubusercontent.com/93295860/155259857-8eba54cb-e923-4235-ac58-c961dc9e0c44.png)

Thank you in advance for any assistance.

Here is my program, in case that helps:
![image](https://user-images.githubusercontent.com/93295860/155259896-8ffc050f-27f3-45c9-be63-32e17b598603.png)

**Comment by mofirouz** [comment]
Hiya - thanks for reporting this. We'll take a look and respond (cc @redbaron). In the meantime, we are experimenting with overhauling the C++ SDK - if you are open to it, I'd love to learn a little bit more about what you are building, target deployment and integration so that we can ensure the new C++ SDK works for you. Please email me at mo@heroiclabsDOTcom - thanks!

**Comment by jkaplan55** [comment]
Hi Mo,  I sent some additional information to your email.  Any news on what's happening here with MacOS build?  Am I missing something from the instructions?  

My project is ready for release just as soon as I can get Nakama to build on MacOS.  Thank you for taking a look.

**Comment by jkaplan55** [comment]
Greetings!

I am encountering the same issue with v2.4.1.  I have attached my project file (it's quite small).  I believe I've followed the instructions in the Readme precisely.  Would it be possible for somebody to take a look at this.  Any feedback, even "it works fine on my computer," would be a big help.

I am missing out on important opportunities to share my work because I cannot get Nakama to build on MacOS.  Any assistance would make a big different.  Thank you!

[Nakama MacBuildTest.zip](https://github.com/heroiclabs/nakama-cpp/files/8247820/Nakama.MacBuildTest.zip)

**Comment by jkaplan55** [comment]
An update here.  It looks like the linker errors are occuring when I create the default client.

This builds:
```
    NLogger::initWithConsoleSink(NLogLevel::Debug);
    NClientPtr client;
    NClientParameters parameters;
    //client = createDefaultClient(parameters);
```

This gives linker errors related to boost, as picture above.:
```
    NLogger::initWithConsoleSink(NLogLevel::Debug);
    NClientPtr client;
    NClientParameters parameters;
    client = createDefaultClient(parameters);
```

Getting pretty desperate here.  I hope someone can help.  Thank you!

**Comment by lugehorsam** [comment]
Hey @jkaplan55 we've reworked the build system and this issue should be resolved.

**Comment by jkaplan55** [comment]
I'm so glad to hear this is released!  Thank you!
