### ISSUE TITLE
Build build_windows.py is failed

### ISSUE THREAD

**Issue by samhero11011** [heroiclabs/nakama-cpp#56]
I need to build client to .dll.
I do not build build_windows.py.
src.obj : error LNK2019: 无法解析的外部符号 __imp_pthread_create，函数 main 中引用了该符号 [C:\Users\Administrator\Desktop\nakamaCppClient\nakama\CMakeFiles\CMakeTmp\cmTC_70533.vcxproj]

src.obj : error LNK2019: 无法解析的外部符号 __imp_pthread_detach，函数 main 中引用了该符号 [C:\Users\Administrator\Desktop\nakamaCppClient\nakama\CMakeFiles\CMakeTmp\cmTC_70533.vcxproj]

src.obj : error LNK2019: 无法解析的外部符号 __imp_pthread_exit，函数 main 中引用了该符号 [C:\Users\Administrator\Desktop\nakamaCppClient\nakama\CMakeFiles\CMakeTmp\cmTC_70533.vcxproj]

src.obj : error LNK2019: 无法解析的外部符号 __imp_pthread_join，函数 main 中引用了该符号 [C:\Users\Administrator\Desktop\nakamaCppClient\nakama\CMakeFiles\CMakeTmp\cmTC_70533.vcxproj]

src.obj : error LNK2019: 无法解析的外部符号 pthread_atfork，函数 main 中引用了该符号 [C:\Users\Administrator\Desktop\nakamaCppClient\nakama\CMakeFiles\CMakeTmp\cmTC_70533.vcxproj]

C:\Users\Administrator\Desktop\nakamaCppClient\nakama\CMakeFiles\CMakeTmp\Debug\cmTC_70533.exe : fatal error LNK1120: 5 个无法解析的外部命令 [C:\Users\Administrator\Desktop\nakamaCppClient\nakama\CMakeFiles\CMakeTmp\cmTC_70533.vcxproj]

**Comment by lugehorsam** [comment]
Hey @samhero11011 we've reworked the build system and you should no longer receive this error.
