### ISSUE TITLE
Headers missing from v1.60 release?

### ISSUE THREAD

**Issue by jkaplan55** [heroiclabs/nakama-cpp#97]
Greetings,

I downloaded v2.6.0 release for win-x64 and was looking forward to adding it to my Cmake project.

'find_package(nakama-sdk)' worked happily enough, but I wasn't able to find header files anywhere in the release folder. 

The readme says "We provide headers and binaries for all supported platforms in our releases section."  but I am not finding the headers anywhere.  Please let me know if I'm missing something.  Thank you!

**Comment by lugehorsam** [comment]
This was resolved in our latest release, I apologize for the missing headers.
