### ISSUE TITLE
C++ CLient SSL verification problem

### ISSUE THREAD

**Issue by zzkcaesar** [heroiclabs/nakama-cpp#98]
Greeting Developers:

When I use the nakama-cpp-2.5.1 to set a client with SSL, I encountered the problem : 
**"[Nakama::RestClient::reqError] NError: ConnectionError
message: [NHttpClientCppRest::request] exception: Error in SSL handshake
start error , error message:message: [NHttpClientCppRest::request] exception: Error in SSL handshake"**

I just set the parameter.ssl to true.  And the nakama server opened the ssl feature also.

And I have checked the source code of the nakama-cpp-2.5.1, I didn't find any place where could import the certificate.

I was wondering if there is any way to implement ssl communication to the server using nakama-cpp-2.5.1. 

Thanks!!

**Comment by lugehorsam** [comment]
Hey @zzkcaesar I'm not sure what platform you were on but could you try the latest release to see if you still have an issue?
